controllers/RbacController.php
<?php

namespace app\controllers;

use yii\filters\VerbFilter;
use Yii;

use app\models\Login;
use app\components\MultidimensionArraySearchHelper;

class RbacController extends \yii\web\Controller
{
    private $rc;
    
    public function __construct($id, $module, $config = array()) {
        $this->rc = new \ReflectionClass(get_class());
        parent::__construct($id, $module, $config);
    }

    public function behaviors() {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }
    
    /**
     * @permission viewusers
     */
    public function actionIndex()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $searchModel = new \app\models\UserSearch;
        $params = Yii::$app->request->getQueryParams();
        $dataProvider = $searchModel->search($params);
                
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        ]);
    }

    /**
     * @permission viewrole
     */
    public function actionRoles()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $auth = Yii::$app->authManager;
        $dataProvider = new \yii\data\ArrayDataProvider([
            'allModels' => $auth->getRoles()
        ]);        
        
        return $this->render('roles', [
            'roles' => $dataProvider
        ]);
    }
    
    /**
     * @permission addrole
     */
    public function actionAddRole()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $model = new \app\models\RoleForm;
          
        if($model->load(\Yii::$app->request->post()))
        {
            $role = new \yii\rbac\Role;
            $role->name = $model->name;
            $role->type = \yii\rbac\Item::TYPE_ROLE;
            $role->description = $model->description;
            $role->createdAt = time();
            $role->updatedAt = time();
            
            \Yii::$app->authManager->add($role);
            
            return $this->redirect(['roles']);
        }
        
        return $this->render('add-role', [
            'model' => $model
        ]);
    }

    /**
     * @permission viewroleperms
     */
    public function actionRolePermissions($role)
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $auth = \Yii::$app->authManager;
        $model = $auth->getRole($role);
        $assignedPermissions = $auth->getPermissionsByRole($role);
        $allPermissions = $auth->getPermissions();
        
        $postedData = \Yii::$app->request->post();
        if(isset($postedData) && !empty($postedData))
        {
            foreach ($postedData['perm'] as $data) 
            {
                
                $exists = array_key_exists($data, $assignedPermissions);
                if (!$exists)
                {    
                    $auth->addChild($model, $allPermissions[$data]);
                }
            }
            //redirect to success page
        }
        
        return $this->render('role-permissions', [
            'role' => $model,
            'assignedPermissions' => $assignedPermissions,
            'allPermissions' => $allPermissions
        ]);
    }

    /**
     * @permission viewperms
     */
    public function actionPermissions()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $controllers = Yii::$app->metaInfo->getAll();
        
        /*$role = $auth->getRole('admin');
        $auth->assign($role, 1);*/
        //$can = Yii::$app->user->can('createPropertyOwner');
        $post = Yii::$app->request->post();
        
        if(isset($post) && !empty($post))
        {
            $auth = Yii::$app->authManager;
        
            /*
             * check if the posted permissions already exist in the db
             * skip those that already to
             */
            $existingPerms = (new \yii\db\Query())
                    ->select('name')
                    ->from('auth_item')
                    ->where([
                        'type' => 2,
                        'name' => $post['perm']
                    ])
                    ->all();
            
            foreach ($post['perm'] as $perm)
            {
                $foundKey = MultidimensionArraySearchHelper::Search($perm, $existingPerms);
                
                //tis a new permission add it to the db
                if(empty($foundKey))
                {
                    $persistedPerm = $auth->createPermission($perm);
                    $auth->add($persistedPerm);
                }
            }
            
        }
        
        return $this->render('permissions', $controllers);
    }

    /**
     * @permission assignroles
     */
    public function actionRoleToUser($id)
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $auth = \Yii::$app->authManager;
        $model = Login::find()
                ->select(['login.emailaddress', 'login.status', 'e.name', 'login.datecreated', 
                    'e.entitytype', 'ai.item_name'])
                ->where(['login.id' => $id])
                ->innerJoin('entity e', 'login.entityref = e.id')
                ->leftJoin('auth_assignment ai', 'login.id = ai.user_id')
                ->one();
        $roles = $auth->getRoles();
                
        $postedData = \Yii::$app->request->post();
        if(isset($postedData) && !empty($postedData))
        {
            $newRole = $postedData['role'];
            $role = $roles[$postedData['role']];
            $auth->assign($role, $id);
            
            //redirect to result page
        }
        
        return $this->render('role-to-user', [
            'model' => $model,
            'roles' => $roles
        ]);
    }
}

views/rbac/add-role.php
<?php
use yii\helpers\Html;

$this->title = 'Create new role';
$this->params['breadcrumbs'][] = ['label' => 'List System roles', 'url' => ['roles']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-header">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

<?php $form = yii\widgets\ActiveForm::begin(); ?>
    <?= $form->field($model, 'name')->textInput(['maxlength' => 60]) ?>

    <?= $form->field($model, 'description')->textArea(['rows' => 3, 'cols' => 40]) ?>

    <div class="form-group">
        <?= Html::submitButton('Create', ['class' => 'btn btn-success']) ?>
    </div>
<?php yii\widgets\ActiveForm::end(); ?>

views/rbac/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'List users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-header">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

<?php yii\widgets\Pjax::begin(); ?>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'datecreated',
            'emailaddress',
            [
                'attribute' => 'status',
                'label' => 'Status',
                'filter' => \app\models\Login::loginStatusDropDown(),
                'value' => function($model, $index, $dataColumn){
                    return \app\models\Login::loginStatusDropDown()[$model->status];
                }
            ],
            [
                'attribute' => 'Action',
                'format' => 'raw',
                'value' => function($model){
                    return '<a href="'. Yii::$app->urlManager->createUrl(['rbac/role-to-user', 'id' => $model->id]) . '">Roles</a>';
                }
            ]
        ],
    ]); ?>
<?php yii\widgets\Pjax::end(); ?>

views/rbac/permissions.php
<?php
//use yii\widgets\ActiveForm;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
?>
<div class="page-header">
    <h1>Sync any permissions with Db</h1>
</div>

<?php
ActiveForm::begin();
?>
<div class="form-group">
    <?= Html::submitButton('Sync', ['class' => 'btn btn-success']) ?>
</div>
<?php
foreach ($controllers as $controller)
{
    echo "<div class='row'>";
        echo "<h4>". $controller['name'] . "</h4>";
        
        echo "<ul>";
        foreach ($controller['actions'] as $action)
        {
            $perm = $action[1];
            
            if(!empty($perm))
            {
                //print("<input type='checkbox' name='". $perm . "' />" . $action[0] . " - " . $perm);
                print("<input type='hidden' name='perm[". $perm . "]' value='". $perm . "' />" . $action[0] . " - " . $perm);
                print("<br />");
            }
        }
        echo "</ul>";
    echo "</div>";
}
yii\bootstrap\ActiveForm::end();
?>

views/rbac/role-permissions.php
<?php
use yii\helpers\Html;

$this->title = $role->name;
$this->params['breadcrumbs'][] = ['label' => 'System Roles', 'url' => ['roles']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-header">
    <h1>Permissions under role <small><?= $role->name ?></small></h1>
</div>

<?php 
$form = yii\widgets\ActiveForm::begin();

foreach ($allPermissions as $permission)
{
    $exists = \app\components\MultidimensionArraySearchHelper::Search($permission, $assignedPermissions);
    //echo $exists;
    echo "<input type='checkbox' name='perm[]' value='$permission->name' ".(($exists != null) ? 'checked' : "") ." /> ";
    print($permission->name);
    echo "<br />";
}
?>
<div class="form-group">
    <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
</div>
<?php
yii\widgets\ActiveForm::end();
?>

views/rbac/role-to-user.php
<?php
use yii\helpers\Html;

$this->params['breadcrumbs'][] = ['label' => 'List Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->emailaddress;
?>
<div class="page-header">
    <h1>Change user role</h1>
</div>

<div class="form-group">
    Current role: <b><?= $model->item_name ?></b>
</div>
<?php $form = yii\widgets\ActiveForm::begin(); ?>
<div class="form-group">
    Select new role
</div>
<div class="form-group">
    <?= Html::dropDownList('role', '', \yii\helpers\ArrayHelper::map($roles, 'name', 'name'), ['prompt' => '-Select new role-']) ?>
</div>
 
<div class="form-group">
    <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
</div>
<?php
yii\widgets\ActiveForm::end();
?>

views/rbac/roles.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'List System roles';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-header">
    <h1>System roles <small>for RBAC</small></h1>
</div>

<p>
    <?= Html::a('Create Role', ['add-role'], ['class' => 'btn btn-success']) ?>
</p>

<?= GridView::widget([
        'dataProvider' => $roles,
        'columns' => [
            'name',
            'description',
            [
                'attribute' => 'Action',
                'format' => 'raw',
                'value' => function($model){
                    return '<a href="'. Yii::$app->urlManager->createUrl(['rbac/role-permissions', 'role' => $model->name]) . '">Permissions</a>';
                }
            ]
        ],
    ]); ?>