controllers/RentalAccountController.php
<?php

namespace app\controllers;

use \Yii;
use yii\filters\VerbFilter;

use app\models\LatePaymentRentalLogSearch;

class RentalAccountController extends \yii\web\Controller
{
    private $rc;
    
    public function __construct($id, $module, $config = array()) {
        $this->rc = new \ReflectionClass(get_class());
        parent::__construct($id, $module, $config);
    }

    public function behaviors() {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @permission viewrentalaccount
     */
    public function actionIndex()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $searchModel = new \app\models\RentalAccountSearch();
        $params = \Yii::$app->request->queryParams;
        $dataProvider = $searchModel->search($params);
        /*$query = \app\models\Rental::find();
        
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $query,
        ]);*/
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * @permission viewrentalaccount
     */
    public function actionView($id)
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $rental = \app\models\Rental::find()
                ->select(['rental.id', 'rental.accountnumber', 'rental.datecreated', 'rental.rentalperiod', 
                    'rental.amountperperiod', 'rental.depositamount', 'rental.currentbalance', 
                    'rental.lastpaymentdate', 'rental.latepaymentcharge', 'rental.billingstartdate', 'rental.rentalstatus',
                    'u.name as unitname',
                    'p.name as propertyname', 'p.code as propertycode',
                    'e.name as tenantname',
                    'cre.expirydate as expirydate'])
                ->where(['rental.id' => $id])
                ->innerJoin('unit u', 'unitref = u.id')
                ->innerJoin('property p', 'u.propertyref = p.id')
                ->innerJoin('entity e', 'tenantref = e.id')
                ->leftJoin('currentrentalexpiry cre', 'rental.id = cre.rentalid')
                ->one();
        
        return $this->render('view', [
            'model' => $rental
        ]);
    }

    /**
     * @permission listtenantrentalaccounts
     */
    public function actionAccountsForTenant($id)
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $query = \app\models\Rental::find()
                ->select(['rental.id', 'rental.accountnumber', 'rental.datecreated', 'rental.rentalperiod', 
                    'rental.amountperperiod', 'rental.depositamount', 'rental.currentbalance', 
                    'rental.lastpaymentdate', 'rental.latepaymentcharge', 'rental.billingstartdate', 'rental.rentalstatus',
                    'u.name as unitname',
                    'p.name as propertyname', 'p.code as propertycode',
                    'e.name as tenantname',
                    'cre.expirydate as expirydate'])
                ->where(['rental.tenantref' => $id])
                ->innerJoin('unit u', 'unitref = u.id')
                ->innerJoin('property p', 'u.propertyref = p.id')
                ->innerJoin('entity e', 'tenantref = e.id')
                ->leftJoin('currentrentalexpiry cre', 'rental.id = cre.rentalid');
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $query,
        ]);
        
        return $this->render('accounts-for-tenant', [
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * @permission viewrentaltxhistory
     */
    public function actionTransactionhistory($id)
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $query = (new \yii\db\Query())
                ->from('transactionhistory')
                ->where(['rentalref' => $id])
                ->orderBy(['id' => SORT_DESC]);
        
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => $query,
        ]);
                
        return $this->renderAjax('transaction-history', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * @permission searchrental
     */
    public function actionSearch()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        return $this->render('search');
    }
    
    public function actionLatePaymentAccounts()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
        
        $searchModel = new LatePaymentRentalLogSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        $pieChartData = \Yii::$app->db->createCommand("SELECT e.name, COUNT(l.`id`) AS lateaccounts FROM `latepaymentrentallog` l
            INNER JOIN `rental` r ON l.`rentalref` = r.`id`
            INNER JOIN `unit` u ON r.`unitref` = u.`id`
            INNER JOIN `property` p ON u.`propertyref` = p.`id`
            INNER JOIN `entity` e ON p.`propertyownerref` = e.`id`
            WHERE l.`year` = YEAR( current_date( ) )
            AND l.`month` = MONTH( current_date( ) ) 
            GROUP BY e.`id`
            ORDER BY lateaccounts DESC
            LIMIT 0, 5")->queryAll();
        
        return $this->render('late-payment-accounts', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
            'pieChartData' => $pieChartData
        ]);
    }
    
    public function actionLatePaymentAccountsPdf()
    {
        $data = \app\models\Latepaymentrentallog::find()->select(['year', 'month', 'amountcharged', 
            'latepaymentrentallog.datecreated', 'e.name as tenantname'])
                ->innerJoin('rental r', 'rentalref = r.id')
                ->innerJoin('entity e', 'r.tenantref = e.id')
                ->where([
                    'year' => date('Y'),
                    'month' => (date('m') < 10) ? substr(date('m'), 1) : date('m')
                    ])->all();
        $content = $this->renderPartial('late-payment-accounts-pdf', ['data' => $data]);
        
        $pdf = \Yii::$app->pdf;
        $mpdf = $pdf->api;
        $mpdf->WriteHtml($content);
        echo $mpdf->Output('filename', 'D');
        
    }
    
    /**
     * @permission closerentalaccount
     */
    public function actionClose($id)
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        
        $can = Yii::$app->user->can($perm);
        if(!$can)
            throw new \yii\web\NotFoundHttpException('You do no have permission to access the requested page.');
                
        $rentalAccount = \app\models\Rental::find()
                ->where(['id' => $id])
                ->one();
        
        if($rentalAccount->rentalstatus != \app\models\Rental::STATUS_RENTAL_ACTIVE)
            throw new \yii\web\NotFoundHttpException('You cannot close an account that is not active!');
        
        
        //get login so that it can be disabled
        $login = \app\models\Login::find()->where(['entityref' => $id])
                ->one();
        
        $refundedAmount = $rentalAccount->close($login);
        $rentalAccount->save();
        
        return $this->renderAjax('close', [
            'amountRefunded' => $refundedAmount
        ]);
    }
    
    /**
     * @permission approvedepositrefund
     */
    public function actionDepositRefundPendingApproval()
    {
        $perm = $this->rc->getMethod($this->action->actionMethod)->getDocComment();
        $perm = preg_replace('/\W/', "", $perm);
        $perm = substr($perm, 10);
        

views/rental-account/accounts-for-tenant.php
<?php
use yii\grid\GridView;

$this->title = "Rental accounts for " . Yii::$app->user->identity->emailaddress;
?>
<div class="page-header">
    <h1><?= $this->title; ?></h1>
</div>

<?php yii\widgets\Pjax::begin(); ?>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'accountnumber',
            [
                'attribute' => 'rentalperiod',
                'label' => 'rental period (months)'
            ],
            'depositamount',
            'datecreated',
            'amountperperiod',
            'currentbalance',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}'  
            ]
        ],
    ]); ?>
<?php yii\widgets\Pjax::end(); ?>

views/rental-account/close.php
<?php
if ($amountRefunded > 0)
{
    ?>
    <p>The account has been successfully closed. Navigate to the link below to approve deposit refund which has been initiated for the tenant</p>
    <p>
        <?= \yii\helpers\Html::a('Deposit refunds for approval', ['/rental-account/deposit-refund-pending-approval']) ?>
    </p>
    <?php
}
 else {
     ?>
    <p>The account was successfully closed but there was no deposit to be refunded.</p>
<?php
}

views/rental-account/deposit-refund-pending-approval.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Deposit refunds';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-header">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

<?php 
\yii\widgets\Pjax::begin(); 
?>

<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            [
                'attribute' => 'datecreated'
            ],
            [
                'attribute' => 'createdby',
            ],
            [
                'attribute' => 'amount'
            ],
            [
                'attribute' => 'accountnumber'
            ],
            [
                'label' => 'Tenant',
                'attribute' => 'name'
            ],
//            [
//                'class' => 'yii\grid\ActionColumn',
//                'template' => '{view}'  
//            ],
            
        ],
    ]); ?>
<?php 
\yii\widgets\Pjax::end(); 
?>

views/rental-account/index.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = 'Rental Accounts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-header">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

<?php 
\yii\widgets\Pjax::begin(); 
?>

<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'tenantname',
                'label' => 'Tenant'
            ],
            [
                'attribute' => 'billingstartdate',
            ],
            [
                'attribute' => 'amountperperiod',
                'label' => 'Amount/Period'
            ],
            [
                'attribute' => 'depositamount',
                'label' => 'Deposit'
            ],
            [
                'attribute' => 'currentbalance',
                'label' => 'A/c balance'
            ],
            'accountnumber',
            [
                'attribute' => 'rentalstatus',
                'label' => 'Status',
                'filter' => \app\models\Rental::rentalStatusDropDown(),
                'value' => function($model, $index, $dataColumn){
                    return \app\models\Rental::rentalStatusDropDown()[$model->rentalstatus];
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}'  
            ],
            /*[
                'attribute' => 'Action',
                'format' => 'raw',
                'value' => function($model){
                    return '<a href="'. Yii::$app->urlManager->createUrl(['rental-account/view', 'id' => $model->id]) . '">View</a>';
                }
            ]*/
        ],
    ]); ?>
<?php 
\yii\widgets\Pjax::end(); 
?>

views/rental-account/late-payment-accounts-pdf.php
<div>List of late payment accounts as @ <?= date('Y-m-d H:i:s') ?></div>
<div style="float: left; width: 100%;">
<table style="width: 100%;">
    <tr>
        <th>Year</th>
        <th>Month</th>
        <th>Amount charged</th>
        <th>Tenant</th>
    </tr>
<?php
foreach ($data as $dataItem)
{
    ?><tr>
        <td><?= $dataItem['year'] ?></td>
        <td><?= $dataItem['month'] ?></td>
        <td><?= $dataItem['amountcharged'] ?></td>
        <td><?= $dataItem['tenantname'] ?></td>
    </tr>  
<?php
}
?>
</table>
</div>    

views/rental-account/late-payment-accounts.php
<?php
use yii\grid\GridView;
use miloschuman\highcharts\Highcharts;
use yii\web\JsExpression;

$this->title = "Late payment accounts for this month";
?>
<div class="page-header">
    <h1><?= $this->title; ?></h1>
</div>

<?php
$data = array();
foreach($pieChartData as $item)
{
    $arrItem = array();
    $arrItem['name'] = $item['name'];
    $arrItem['y'] = (int)$item['lateaccounts'];
    $data[] = $arrItem;
}

echo Highcharts::widget([
    'scripts' => [
        'themes/grid-light',
    ],
    'options' => [
        'title' => [
            'text' => 'Distribution per owner',
        ],
        
        'series' => [
            [
                'type' => 'pie',
                'name' => '# late customers',
                'data' => $data,
                //'center' => [800, 100],
                'size' => 150,
                'showInLegend' => FALSE,
                'dataLabels' => [
                    'enabled' => FALSE,
                ],
            ],
        ],
    ]
]);
?>
<?php 
echo yii\helpers\Html::a('<i class="fa glyphicon glyphicon-hand-up"></i> Export to pdf', 
    ['/rental-account/late-payment-accounts-pdf'], 
    [
        'class' => 'btn btn-danger',
        'target' => '_blank',
        'data-toggle' => 'tooltip'
    ]);
yii\widgets\Pjax::begin(); ?>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'year',
            [
                'attribute' => 'month',
                'label' => 'month',
                'value' => function($model, $index, $dataColumn){
                    return date('F', mktime(0, 0, 0, $model->month, 10));
                }
            ],
            [
                'attribute' => 'tenantname',
                'label' => 'Tenant'
            ],
            'datecreated',
            'amountcharged'
        ],
    ]); ?>
<?php yii\widgets\Pjax::end(); ?>

views/rental-account/transaction-history.php
<?php
use yii\grid\GridView;
?>

<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'id',
            'datecreated',
            'credit',
            'debit',
            'accounttype',
            'description'
        ],
    ]); ?>

views/rental-account/view.php
<?php
use yii\grid\GridView;
use yii\helpers\Html;

$this->title = $model->accountnumber;
$this->params['breadcrumbs'][] = ['label' => 'Rental Accounts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-header">
    <h1>Account number: <?= Html::encode($this->title) ?></h1>
</div>

<div class="row">
    <div class="col-sm-2">
        Account status
    </div>
    <div class="col-sm-2">
        <?= \app\models\Rental::rentalStatusDropDown()[$model->rentalstatus] ?>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-2">
        Current a/c balance
    </div>
    <div class="col-sm-2">
        <?= $model->currentbalance ?>
    </div>
    <?php
    if($model->rentalstatus == \app\models\Rental::STATUS_RENTAL_ACTIVE)
    {
        ?>
        <div class="col-sm-offset-10">
            <?= Html::a('Close Account', ['rental-account/close', 'id' => $model->id], ['id' => 'closeAccount']) ?>
        </div>
    <?php
    }
    ?>
</div>

<div class="row">
    <div class="col-sm-2">
        Date Created
    </div>
    <div class="col-sm-2">
        <?= $model->datecreated ?>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-2">Billing start date</div>
    <div class="col-sm-2"><?= $model->billingstartdate ?></div>
</div>

<div class="row">
    <div class="col-sm-2">
        Rental period (months)
    </div>
    <div class="col-sm-2">
        <?= $model->rentalperiod ?>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-2">Amount per period</div>
    <div class="col-sm-2"><?= $model->amountperperiod ?></div>
</div>

<div class="row">
    <div class="col-sm-2">
        Last payment date
    </div>
    <div class="col-sm-2">
        <?= $model->lastpaymentdate ?>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-2">Late payment charge (%)</div>
    <div class="col-sm-2"><?= $model->latepaymentcharge ?></div>
</div>

<div class="row">
    <div class="col-sm-2">
        Tenant
    </div>
    <div class="col-sm-2">
        <?= $model->tenantname ?>
    </div>
    
</div>

<div class="row">
    <div class="col-sm-2">
        Property name
    </div>
    <div class="col-sm-2">
        <?= $model->propertyname ?>
    </div>
    <div class="col-sm-1"></div>
    <div class="col-sm-2">Property code</div>
    <div class="col-sm-2"><?= $model->propertycode ?></div>
</div>

<div class="row">
    <div class="col-sm-2">
        Unit name
    </div>
    <div class="col-sm-2">
        <?= $model->unitname ?>
    </div>
    
</div>

<div class="row">
    <div class="col-sm-2">
        Current expiry
    </div>
    <div class="col-sm-2">
        <?= $model->expirydate ?>
    </div>
    
</div>

<div class="row">
<?php
echo yii\jui\Tabs::widget([
    'items' => [
        [
            'label' => 'Transaction History',
            'headerOptions' => ['style' => 'font-weight:bold;'],
            'url' => ['rental-account/transactionhistory', 'id' => $model->id]
        ]/*,
        [
            'label' => 'Sms History',
            'content' => 'content two',
            'headerOptions' => ['style' => 'font-weight:bold'],
            
        ]*/
    ]
]);
?>
</div>

<?php 
yii\bootstrap\Modal::begin(['header' => '<h2>Accout closed successfully</h2>', 'id' => 'modal']);
echo "<div id='modalContent'></div>";
yii\bootstrap\Modal::end();

$jsPath = Yii::getAlias('@web/js/common.functions.js');

$this->registerJsFile($jsPath, ['depends' => \yii\web\JqueryAsset::className()]);
?>